import React from "react";

const ModelAttribution: React.FC = () => {
  return (
    <div className="px-3 py-2 bg-gradient-to-r from-teal-50 to-green-50 dark:from-teal-900/20 dark:to-green-900/20 rounded-lg border border-teal-200 dark:border-teal-800">
      <p className="text-xs font-medium">
        <span className="text-gray-700 dark:text-gray-300">
          This analysis is generated by{" "}
        </span>
        <a
          href="https://huggingface.co/aisingapore/Gemma-SEA-LION-v4-27B-IT"
          target="_blank"
          rel="noreferrer"
          className="text-yellow-600 dark:text-yellow-400 hover:text-yellow-700 dark:hover:text-yellow-300 font-semibold transition-colors"
        >
          Gemma-SEA-LION-v4-27B-IT
        </a>
      </p>
    </div>
  );
};

export default ModelAttribution;
